FROM ubuntu:latest
RUN apt update -y && \
    apt install -y python3 \
                   wget \
                   sudo && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
